### PR TITLE
Add README 

### PR DESCRIPTION
**Pull request by gilteunchoi**
Add README to inform:
- How to update `docs.in.rs`
- How does doc is generated in RustPython
- To see the cute RustPython logo 😃.

### CODE REVIEW

**Comment by gilteunchoi** [comment]
I did not notice that there is an existing PR for readme 😞 
maybe some parts in this PR could be applied after the initial PR?

**Comment by youknowone** [comment]
Thank you! I merged #2

**Comment by gilteunchoi** [comment]
I've added some comments about possible mistakes someone else could made, and also logo.png.

**Review by youknowone — APPROVED** [review]

**Comment by youknowone** [comment]
thank you!

**Pull request merged**
